# Generated by Django 4.0.6 on 2022-07-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0004_passenger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='flights',
        ),
        migrations.AddField(
            model_name='passenger',
            name='flight',
            field=models.ManyToManyField(blank=True, related_name='passengers', to='flight.flight'),
        ),
    ]
