# Generated by Django 4.0.6 on 2022-07-27 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0005_remove_passenger_flights_passenger_flight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='flight',
            new_name='flights',
        ),
    ]
